services:
  # Observability
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # Disable Login form or not
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      # Allow anonymous authentication or not
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      # Role of anonymous user
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus