services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
